### ISSUE TITLE
输入中文名字时会出错

### ISSUE THREAD

**Issue by Vanilla-Yukirin** [Zyyans/Nyahentai-Spider#1]
例如：魂魄妖夢

**Comment by nazhendenb** [comment]
没想到这里也能遇到车车人。 教教我怎么用呀 第一句What are you need?  不管是输入网址 数字都会卡住

**Comment by nazhendenb** [comment]
看了看源码，会用了， 只能按角色下载啊 
PS：0x6864B95C是什么意思？

PS2：可以输入中文名
![image](https://user-images.githubusercontent.com/36919867/98325011-bc9b3100-2028-11eb-9cf5-9f039f7e6fda.png)

PS3：nyahentai 爬虫搜到3个， 另外两个一个是python一个是java，隔壁python的那个输入完ID和tag瞬间弹窗下载成功，我甚至怀疑只有弹窗功能。 java那个我不会用，大佬能教教吗？   输入画廊URL下载才是我真正需要的

**Comment by Vanilla-Yukirin** [comment]
稍等。好久没用了，我再试一试

**Comment by Vanilla-Yukirin** [comment]
`0x6864B95C`是我的某个社交帐号。但是。。。您是在哪里看到的？（害怕

**Comment by nazhendenb** [comment]
> `0x6864B95C`是我的某个社交帐号。但是。。。您是在哪里看到的？（害怕

你个人博客里看到的，因为那个网页404了，我尝试着16进制转换没搞出来结果，以为是404导致的乱码

**Comment by nazhendenb** [comment]
> `0x6864B95C`是我的某个社交帐号。但是。。。您是在哪里看到的？（害怕

话说另外一个你会不会用呀 教教我   java的那个爬虫

**Comment by Vanilla-Yukirin** [comment]
> 话说另外一个你会不会用呀 教教我 java的那个爬虫

我不会java。。。python业余级别的，主学c++

**Comment by Vanilla-Yukirin** [comment]
我现在这个环境不好，code没法快速clone下来

**Comment by nazhendenb** [comment]
> > 话说另外一个你会不会用呀 教教我 java的那个爬虫
> 
> 我不会java。。。python业余级别的，主学c++

我哭了，隔壁作者说停止维护了。  我是万年白嫖怪，不会写代码，只来GitHub偷代码。
大佬看看能不能从这个项目拆出来一个输入画廊URL下载的功能

**Comment by nazhendenb** [comment]
> 我现在这个环境不好，code没法快速clone下来

cmd可以设代理的 打开代理软件之后把下面的port替换成自己的端口号   python似乎只支持http代理

set http_proxy=http://127.0.0.1:port& set https_proxy=http://127.0.0.1:port

端口号为
![image](https://user-images.githubusercontent.com/36919867/98335857-c335a280-2040-11eb-85e9-63845ca2bbfd.png)

**Comment by Vanilla-Yukirin** [comment]
> 我哭了，隔壁作者说停止维护了。 我是万年白嫖怪，不会写代码，只来GitHub偷代码。
>大佬看看能不能从这个项目拆出来一个输入画廊URL下载的功能

谁不是来白嫖的呢……我在爬虫这方面不行啊，python也不强

> cmd可以设代理的

我试试

**Comment by Vanilla-Yukirin** [comment]
但是我还是。。。
![image](https://user-images.githubusercontent.com/51521470/98337115-14df2c80-2043-11eb-9e34-1b957eea6f12.png)

**Comment by Vanilla-Yukirin** [comment]
是我的操作方式不对嘛？（大雾

**Comment by nazhendenb** [comment]
> 但是我还是。。。
> ![image](https://user-images.githubusercontent.com/51521470/98337115-14df2c80-2043-11eb-9e34-1b957eea6f12.png)

因为不存在这个角色，魂魄妖梦的罗马音/英语开头字母是K 所以第一步要输入K,等他检索完成后 会生成一个txt文件，第二步的name只能从这里面找,然而不管是罗马音还是简繁体字都没有找到魂魄妖梦。 这应该是网站机制的问题，和脚本没太大关系
![image](https://user-images.githubusercontent.com/36919867/98337335-6be50180-2043-11eb-8c44-d30cdc3c4dbf.png)

**Comment by nazhendenb** [comment]
> > 但是我还是。。。
> > ![image](https://user-images.githubusercontent.com/51521470/98337115-14df2c80-2043-11eb-9e34-1b957eea6f12.png)
> 
> 因为不存在这个角色，魂魄妖梦的罗马音/英语开头字母是K 所以第一步要输入K,等他检索完成后 会生成一个txt文件，第二步的name只能从这里面找,然而不管是罗马音还是简繁体字都没有找到魂魄妖梦。 这应该是网站机制的问题，和脚本没太大关系
> ![image](https://user-images.githubusercontent.com/36919867/98337335-6be50180-2043-11eb-8c44-d30cdc3c4dbf.png)

我在试着从里面抠出来一个URL下载的功能（好难啊

**Comment by Zyyans** [comment]
你们好，谢谢你们认真使用咱的软件。
这是咱写下来个人使用和私下传播的作品，所以它的交互非常反人类。
很抱歉现在才回复你们，如果你们还有需要咱可以提供帮助。反正咱很闲。

**Comment by Vanilla-Yukirin** [comment]
> 我在试着从里面抠出来一个URL下载的功能（好难啊

@railannad 

很抱歉当时没有立即回复您，因为我实在是不会用python写爬虫，现在还是不会。

请容许我以后再来这里和大家交流吧，先去应付学校了。

正好Owner也来了，祝你成功吧！

**Comment by Vanilla-Yukirin** [comment]
故地重游。

现在喵绅士是没了嘛？

**Comment by Zyyans** [comment]
大概是吧……和它同源的Erocool也打不开很久了。

**Comment by Vanilla-Yukirin** [comment]
昔人依旧在，网站却已封。旧时求真者，有缘再相会。
